const { NEXT_PUBLIC_KEYCLOAK_REALM } = process.env;
const { NEXT_PUBLIC_KEYCLOAK_URL } = process.env;
const { NEXT_PUBLIC_KEYCLOAK_CLIENT_ID } = process.env;
const { NEXT_PUBLIC_PAYMENT_URL } = process.env;
const { NEXT_PUBLIC_BASE_PATH } = process.env;
const { NEXT_PUBLIC_WALLET_URL } = process.env;

export {
  NEXT_PUBLIC_PAYMENT_URL,
  NEXT_PUBLIC_WALLET_URL,
  NEXT_PUBLIC_BASE_PATH,
  NEXT_PUBLIC_KEYCLOAK_REALM,
  NEXT_PUBLIC_KEYCLOAK_URL,
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID,
};
