export default {
  common: {
    homeTitle: "GROUPADO PAYMENT",
    // home
    goToDashboard: "Aller au Tableau de Bord",
    hero1: "",
    hero2: "",
    SignUp: "S'inscrire",
    // dashboard
    dashboard: "Tableau de Bord",
    merchants: "Marchants",
    websites: "Sites Internet",
    environments: "Environnements",
    transactions: "Transactions",
    profile: "Profile",
    // display merchant
    displayMerchantTitle: "Choisissez un marchand",
    dialogCancel: "Annuler",
    dialogAgree: "Accepter",
    delete: "Effacer",
    edit: "Éditer",
    firstName: "Prénom",
    lastName: "Nom",
    email: "E-mail",
    password: "Mot de passe",
    address: "Adresse",
    phoneNumber: "Numéro de téléphone",
    currency: "Devise",
    submit: "Envoyer",
    country: "Pays",
    status: "Status",
    actions: "Actions",
    id: "ID",
    viewMerchant: "View Afficher le merchand",
    merchantAlertTitle: "Alert",
    merchantAlertContent: "Voulez-vous supprimer ce marchand ?",
    // merchant form
    merchantFormEnabled: "activé",
    merchantFormDisabled: "désactivé",
    merchantFormBlocked: "bloqué",

    addNewMerchant: "Ajouter un nouveau marchand",
    // Global Form validation
    emailReq: "* l'e-mail est obligatoire",
    emailValid: "Veuillez entrer une adresse e-mail valide",
    phonenotValid: "Numéro de téléphone invalide",
    phoneRequired: "le numéro de téléphone est obligatoire",
    lastnemaRequired: "* votre nom est obligatoire",
    lastnameMincaracter: "* au moins 3 caractères!",
    firstnameRequired: "* votre prénom est obligatoire",
    firstnameMincaracter: "* au moins 3 caractères!",
    addressRequired: "* l'address est obligatoire",
    passwordRequired: "* le mot de passe est obligatoire",
    currencyRequired: "* le devise est obligatoire",
    statusRequired: "* le status est obligatoire",
    passwordPlaceholder: "entrer le mot de passe",
    addressPlaceholder: "entrer votre address",
    phonePlaceholder: "entrer votre numéro de téléphone",
    firstnamePlaceholder: "entrer votre prénom",
    lastnamePlaceholder: "entrer votre nom",
    emailPlaceholder: "entrer votre adresse e-mail",
    passwordMincaracter: "* au moins 5 caractères!",
    websitenameRequired: "* required website name",
    websiteDescRequired: "* required website description",
    websiteUrlRequired: "* required  website url",
    websiteCommisionRequired: "* required website commision",
    successUrlRequired: "* required  website success url",
    failUrlRequired: "* required website failed url",
    notificationUrlRequired: "* required website url notifiction",
    paymentMethodsRequired: "* required website payment method(s)",
    websitename: "enter website name",
    url: "website url",
    name: "Nom site website",
    websiteUrl: "enter website url",
    websiteDescription: "enter website description",
    methods: "website methods",
    ADD_WEBSITE: "Ajouter un site Web",
    UPDATE_WEBSITE: "Mettre à jour le site Web",
    UPDATE_WEBSITE_THEME: "Mettre à jour le théme de site Web",
    websiteFailUrl: "enter website failed url",
    websiteSuccessUrl: "enter website success url",
    websiteNotificationUrl: "enter website notification url",
    NotificationUrl: "notification url",
    websiteFormPaypal: "paypal",
    websiteFormCheckout: "checkout",
    websiteFormSobflous: "sobflous",
    websiteFormGpgcheckout: "gpg checkout",
    NA: "N/A",
    paymentMethod: "Methode",
    Name: "Nom",
    filterByWebsite: "Filtrer par sites Web",
    filterByStatus: "Filtrer par statut",
    filterByMethods: "Filtrer par modes de paiement",
    // withdraw page
    goBack: "Retournez à la page d'accueil",
    tnd: "TND",
    errorMinOneTND:
      "Veuillez entrer une valeur en Dinars avec un minimum de 1 TND !",
    withdrawFrom: "retirer de",
    confirmWithdraw: "Confirmer la demande de retrait :",
    confirmWithdrawContent: "Accepter de retirer {amount} TND de sobflous ?",
    withdraw: "Retrait",
    amount: "Montant",
    active: "Actif",
    inactive: "Inactif",
    report: "Rapport",
    transactionsCount: "Nombre de transactions",
    chartTitle: "Graphique des transactions par date",
    loadingCsv: "Chargement du CSV...",
    exportBtn: "Exporter CSV",
    creationDate: "Date de création",
    filterByDate: "Filtrer par date",
    resetFilters: "Réinitialiser les filtres",
    all: "Tous",
    transactionId: "ID du Transaction",
    close: "Fermer",
    // wallets
    wallets: "Portefeuilles",
    displayWalletsTitle: "Portefeuilles",
    userId: "Identifiant de l'utilisateur",
    balance: "Solde",
    enableBtn: "activer/désactiver",
    enable: "Activer",
    disable: "Désactiver",
    selectWebsite: "Veuillez sélectionner un site Web dans la liste ci-dessus",
    disableWalletMsg:
      "Le portefeuille est déjà activé, voulez-vous désactiver le portefeuille ?",
    enableWalletMsg:
      "Le portefeuille n'est pas activé, voulez-vous activer le portefeuille ?",
    deposit: "faire un dépôt",
    increaseBalance: "Augmenter l'équilibre",
    increaseBtn: "Augmenter",
    decreaseBalance: "Diminuer le solde",
    decreaseBtn: "Diminuer",
    walletTransactionsTitle: "Liste des Transactions",
    walletHistoryTitle: "Liste de l'historique",
    processing: "Traitement en cours...",
    amountError: "Ajouter un montant valide !",
    sender: "expéditeur",
    receiver: "récepteur",
    type: "Type",
    createdAt: "Créé à",
    showHistory: "Afficher l'historique",
    commentOptional: "commentaire (optionnel)",
    showTransactions: "Afficher les transactions",
    confirmBankTransfer: "Confirmer le virement bancaire",
    messageBankTransfer:
      "Êtes-vous sûr de vouloir approuver cette transaction ?",
    approve: "Approuver",
    primaryColor: "couleur primaire",
    editGatewayTheme: "Modifier le Thème ",
    more: "Détails",
  },
};
